const date = new Date()
console.log("data sem alteracao do set: "+date)
date.setFullYear("2000")
console.log(date)
date.setMonth("5")
console.log(date)
date.setDate("18")
console.log(date)
date.setTime("22:22:22")